title: jonathanseyfried.net
description: Personal and academic website for Jonathan Seyfried
url: http://jonathanseyfried.net
permalink: :categories/:title
safe: true
markdown: kramdown
environment: production
